# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\x1a\n\x08RpcInput\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1b\n\tRpcOutput\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xe9\x01\n\nCalculator\x12\x35\n\x06Square\x12\x14.calculator.RpcInput\x1a\x15.calculator.RpcOutput\x12\x32\n\x03\x41\x64\x64\x12\x14.calculator.RpcInput\x1a\x15.calculator.RpcOutput\x12\x37\n\x08Subtract\x12\x14.calculator.RpcInput\x1a\x15.calculator.RpcOutput\x12\x37\n\x08Multiply\x12\x14.calculator.RpcInput\x1a\x15.calculator.RpcOutputB6\n\x1bio.grpc.examples.calculatorB\x0f\x43\x61lculatorProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.calculatorB\017CalculatorProtoP\001\242\002\003HLW'
  _globals['_RPCINPUT']._serialized_start=32
  _globals['_RPCINPUT']._serialized_end=58
  _globals['_RPCOUTPUT']._serialized_start=60
  _globals['_RPCOUTPUT']._serialized_end=87
  _globals['_CALCULATOR']._serialized_start=90
  _globals['_CALCULATOR']._serialized_end=323
# @@protoc_insertion_point(module_scope)
